### PR TITLE
Ability to generate all hex colours

### PR DESCRIPTION
**Pull request by Souravgoswami**
Added ruby code that can translate cursors to a defined colour.

The make procedure and all remains same. To generated a defined cursor, the user is intended to run generator/convert.rb. They can define the colours in the generator/colours.conf in hex (in #ff55ff or #f5f format).

Building now takes a bit longer as expected, due to the increased amount of cursors. I have added "spark" colours, which are generally brighter ones.

### CODE REVIEW

**Comment by Souravgoswami** [comment]
Added ruby code that can translate cursors to a defined colour.

The make procedure and all remains same. To generated a defined cursor, the user is intended to run generator/convert.rb. They can define the colours in the generator/colours.conf in hex (in #ff55ff or #f5f format).

Building now takes a bit longer as expected, due to the increased amount of cursors. I have added "spark" colours, which are generally brighter ones.

**Comment by Souravgoswami** [comment]
Updated readme and fixed typo

**Comment by varlesh** [comment]
Usually i'm use sed for that - it's easy for all colors))
Thx for PR, but some themes not possible generate from base_files.
For example, white cursors - generate white logo on white background, it's merged colors and not good:
https://github.com/Souravgoswami/oreo-cursors/blob/master/src/oreo_white_cursors/alias.svg
https://github.com/varlesh/oreo-cursors/blob/master/src/oreo_white_cursors/alias.svg

Also on black curscors changed no-drop background:
https://github.com/Souravgoswami/oreo-cursors/blob/master/src/oreo_black_cursors/dnd-no-drop.svg
https://github.com/varlesh/oreo-cursors/blob/master/src/oreo_black_cursors/no-drop.svg

**Comment by Souravgoswami** [comment]
Yes, the background stays pretty much the same. The script can be modified, so the shadow colour is also user definable. By default it should be black (the one currently used).

I intentionally did it, because white shadow will look like glowing cursor! Oh and because it's SVG, we can also define the shadow, like some CSS property!

**Comment by varlesh** [comment]
I mean about background and label - not shadow.
On your generator have white label on white background - it's not right with original.
Your:
https://github.com/Souravgoswami/oreo-cursors/blob/master/src/oreo_white_cursors/copy.svg
Original:
https://github.com/varlesh/oreo-cursors/blob/master/src/oreo_white_cursors/copy.svg
Maybe as solution added white & black cursors to blacklist.
Not sure about shadows option... I think black shadow good looking with all colors.

**Comment by Souravgoswami** [comment]
Got it! I think the cursor is complete, it has all the cursors needed:
[The cursor Property](https://www.w3schools.com/cssref/tryit.asp?filename=trycss_cursor)

The only thing we do is changing the colours.

What we can do is replace the .svg extension with something like .oreo, and they will have a foreground colour, shadow colour, and the label colour.



So we need to modify the svg, it will have "#{colour}" in place of the hex colour, say #F55. The ruby program will insert colours there.

So whenever you edit them in inkscape (for example), you will need to open the svg in editor, change the bg colour to #{background}, foreground colour to #{foreground}, label colours to #{label}. The script will inject colours there after reading what's in your config file.

So in your config file, you will need to specify this:

```
spark_blue = #4E81ED, shadow = #ff0, label = #fff
```

If the shadow and label isn't specified, they will be default to #000 and #fff.
This will help users to generate any colour they want.

**Comment by Souravgoswami** [comment]
Hello I have added commit to make for the aforementioned changes.

You can review it and accept pull request if it doesn't violate oreo-cursors' look and feel. It's also ok if you think it should go to a separate repo. Please let me know.

**Comment by varlesh** [comment]
Merged. Big thx. I'm change label color for pirate/wayland/xorg

**Comment by varlesh** [comment]
@Souravgoswami `src` folder now it's only preview for result generator from base files?

**Comment by varlesh** [comment]
I think better solution for specific icons - it's ignore all attributes:

- color-picker.svg.oreo
- dnd-no-drop.svg.oreo
- no-drop.svg.oreo
- not-allowed.svg.oreo
- pirate.svg.oreo
- wayland-cursor.svg.oreo
- x-cursor.svg.oreo

And i think shadow not needed change - it's unnecessary option.

**Comment by varlesh** [comment]
error with convert:
```
Traceback (most recent call last):
        3: from ./convert.rb:49:in `<main>'
        2: from ./convert.rb:49:in `each_with_index'
        1: from ./convert.rb:49:in `each'
./convert.rb:70:in `block in <main>': undefined method `then' for ["black ", " #424242\n"]:Array (NoMethodError)
```

**Comment by varlesh** [comment]
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
ubuntu 18.04

**Comment by Souravgoswami** [comment]
Oh LOL. Ruby 2.5.1 didn't have the Kernel#then() method! It has Kernel#yield_self... I thought distributions have Ruby 2.6 at least...

So this works from Ruby 2.6 to Ruby 2.7. Ruby 2.6 is now more than a year old I guess...

But as you are running with Ruby 2.5.1, the program needs some changes. I have Ruby 2.3 to Ruby 2.7 for test. I will test with the lower minor versions, and will run from Ruby 2.4 to the latest Ruby... Just a moment, it's not really that hard ;)

**Comment by Souravgoswami** [comment]
I have fixed the issue. It should support Ruby 2.4 and beyond now. If you think it should go to a separate branch, it's fine... But you can use it if it helps ;)

**Pull request merged**
