### PR TITLE
Ruby 2.4 support in convert.rb

### LINKED ISSUE #9: New spark colors
@Souravgoswami 
Not good looking this colors:
`spark_light_pink`  - very faded. Maybe better add contrast on backround, for example `#ff91c7`
`spark_yellow_cursors` - it's more lime color and merged with label too. As solution rename to `lime` & change label to `#2e7d32`

### LINKED ISSUE #11: Add Ruby 2.4+ support
Convert.rb only supported Ruby 2.6+. But various distributions using Ruby 2.4+ and Ruby 2.5+ should be supported.

### PR DESCRIPTION
**Pull request by Souravgoswami**
1. Ruby 2.4+ supported. Previously it used to support Ruby 2.6+ Resolves #11 
2. Lime colour instead of spark yellow colour Resolves #9.
3. Spark Pink Lite is modified to a deeper colour Resolves #9.

### CODE REVIEW

**Comment by varlesh** [comment]
@Souravgoswami Please solve conflicts. I can't merge it

**Comment by Souravgoswami** [comment]
Ok I am trying to solve the conflicts

**Comment by Souravgoswami** [comment]
Now it's all done! For any script bug, please mention me.

Also, the ruby script has no dependency. So it should support future version of Ruby, for 4 - 5 years at least unless they make a lot of changes to Ruby.

After the PR is closed, I will generate the cursors waiting right now (conflicting files), and will keep that.
The generation of the various coloured cursors is up to you.

For any feature request, or urgent need, you can write me at souravgoswami@protonmail.com.

Hope the script will help to generate more colourful cursors :)

**Comment by varlesh** [comment]
worked fine )))

**Pull request merged**
